### ISSUE TITLE
Plugin not working with Grails 3.3.x

### ISSUE THREAD

**Issue by hugheba** [grails-plugins/grails-spring-security-cas#20]
Looks like they've removed the FilterRegistrationBean in Grails 3.3.x which causes the error on boot...

```
Configuring Spring Security CAS ...
2017-06-28 18:01:15.201 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean
        at grails.plugin.springsecurity.cas.SpringSecurityCasGrailsPlugin$_doWithSpring_closure1.doCall(SpringSecurityCasGrailsPlugin.groovy:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

Mac OS X 10.12.5
Java 1.8.131
Grails 3.3.0.RC1

**Comment by sdelamo** [comment]
Have you tried defining the Spring Security Core dependency explicitly. Such as: 
```
   compile 'org.grails.plugins:spring-security-cas:3.0.1'
   compile 'org.grails.plugins:spring-security-core:3.2.0.M1'
```

Version 3.2.0.M1 is compatible with Grails 3.3.

**Comment by hugheba** [comment]
@sdelamo Yes I am already using `'org.grails.plugins:spring-security-core:3.2.0.M1'`.

**Comment by spmcewen** [comment]
@hugheba @sdelamo I'm having the same issue with Grails 3.3, spring security core 3.2.0.M1 and spring security cas 3.0.1:

```
compile 'org.grails.plugins:spring-security-cas:3.0.1'
compile 'org.grails.plugins:spring-security-core:3.2.0.M1'
```

I found that disabling single signout works around the problem:
```
              cas:
                  useSingleSignout: false
```

**Comment by sdelamo** [comment]
The latest version should work with 3.3.x. 

` compile 'org.grails.plugins:spring-security-cas:3.1.0'`

Please reopen if the error is still ocurring.
